apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd-system
spec:
  project: default
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-cd
    targetRevision: 7.8.2
    helm:
      valueFiles:
      - $values/argocd/values.yaml
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            server:
              ingress:
                annotations:
                  external-dns.alpha.kubernetes.io/hostname: argocd.<path:secrets/common/infra#network_dns_zone>.
                hostname: deploy.<secrets/secrets/common/infra#network_dns_zone>
            global:
              domain: deploy.<secrets/secrets/common/infra#network_dns_zone>
  - repoURL: https://github.com/InputObject2/iac-kubernetes-cluster.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  syncPolicy:
    automated:
      prune: false  # Do not delete existing resources yet
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
